# Generated by Django 2.2 on 2021-09-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_deal_product_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='test.jpeg', null=True, upload_to='event/'),
        ),
    ]
